name: Push Changes to Another Repo

on:
  schedule:
    - cron: "*/7 * * * *" # Runs every 7 minutes
  workflow_dispatch:

jobs:
  push-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository A
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install

      - name: Run push script
        run: node app.js
        env:
          PAT: ${{ secrets.QUILO_SOMAN_PAT }}
